apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-app-deplpoyment
  labels:
    app: my-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-todo-app
  template:
    metadata:
      labels:
        app: my-todo-app
    spec:
      containers:
      - name: my-todo-app-container
        image: streak2508/my-node-app:${BUILD_NUMBER}
        ports:
        - containerPort: 8000
